services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: rails s -b 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - './:/home/appuser/app'
      - 'gems:/usr/local/bundle'

volumes:
  gems: